import type { VfsPersistenceStore } from '@/app/stores/vfs-persistence-store'
import type { ChatVfsVersionEntry, VfsCommitSource } from '@/infra/persistence/vfs-chat-metadata.schema'

/**
 * Create a lightweight commit metadata entry.
 *
 * `source` exists to attribute commits to one of three categories:
 * - `'tool'`: generated by successful virtual tool batches (transactional persist-on-success).
 * - `'manual'`: initiated by user/UI actions (explicit save, template overwrite checkpoints, etc.).
 * - `'system'`: internal/system events (migration, auto-repair, future background sync, etc.).
 *
 * The entry intentionally does not include full snapshot payload; it is meant to be cheap to
 * append and easy to display/filter in UI.
 */
function createVersionEntry(source: VfsCommitSource, summary: string, changedFiles: string[]): ChatVfsVersionEntry {
  return {
    id: `commit-${Date.now()}-${Math.random().toString(16).slice(2, 8)}`,
    timestamp: Date.now(),
    source,
    summary,
    changedFiles,
  }
}

/**
 * Chat-scoped VFS version history service.
 *
 * This service records commit *metadata* into chat persistence (`chatVfsVersions`) so callers can
 * build a user-facing history, diagnostics, or rollback UX.
 *
 * Note: the persistence model is append-only; entries are not mutated in place.
 */
export class ChatVfsVersionService {
  constructor(private readonly store: VfsPersistenceStore) {}

  /**
   * Record a commit produced by a successful tool batch.
   *
   * Use this when a transactional tool execution has been persisted to chat snapshot.
   */
  commitByToolBatch(summary: string, changedFiles: string[]): ChatVfsVersionEntry {
    return this.commit('tool', summary, changedFiles)
  }

  /**
   * Record a commit produced by an explicit manual action (user/UI).
   *
   * Examples: “save”, template overwrite checkpoints, or other user-driven changes.
   */
  commitByManualSave(summary: string, changedFiles: string[]): ChatVfsVersionEntry {
    return this.commit('manual', summary, changedFiles)
  }

  /**
   * Record a system-initiated commit.
   *
   * Examples: migrations, auto-repair, or other internal maintenance events.
   */
  commitSystem(summary: string, changedFiles: string[]): ChatVfsVersionEntry {
    return this.commit('system', summary, changedFiles)
  }

  /** Return commits in insertion order (oldest → newest). */
  listCommits(): ChatVfsVersionEntry[] {
    return [...this.store.getState().chat.chatVfsVersions]
  }

  /**
   * Append a commit entry to the chat history.
   *
   * This method is intentionally append-only to preserve an auditable sequence.
   */
  private commit(source: VfsCommitSource, summary: string, changedFiles: string[]): ChatVfsVersionEntry {
    const entry = createVersionEntry(source, summary, changedFiles)
    // 仅追加，不就地修改历史，保持提交序列可追踪。
    this.store.updateChat((draft) => ({ ...draft, chatVfsVersions: [...draft.chatVfsVersions, entry] }))
    return entry
  }
}
