export const VFS_ERROR_CODES = {
  VIEW_OPEN_FAILED: 'E_VIEW_OPEN_FAILED',
  EDIT_OPEN_FAILED: 'E_EDIT_OPEN_FAILED',
  STATUS_TOGGLE_FAILED: 'E_STATUS_TOGGLE_FAILED',
  DELETE_FAILED: 'E_DELETE_FAILED',
  RENAME_FAILED: 'E_RENAME_FAILED',
  STRATEGY_APPLY_FAILED: 'E_STRATEGY_APPLY_FAILED',
  SLIDESHOW_OPEN_FAILED: 'E_SLIDESHOW_OPEN_FAILED',
  SAVE_FAILED: 'E_SAVE_FAILED',
  ROLLBACK_FAILED: 'E_ROLLBACK_FAILED',
  BATCH_ROLLBACK_FAILED: 'E_BATCH_ROLLBACK_FAILED',
  LOG_FETCH_FAILED: 'E_LOG_FETCH_FAILED',
  RENDER_FAILED: 'E_RENDER_FAILED',
  COMMIT_APPLY_FAILED: 'E_COMMIT_APPLY_FAILED',
  HISTORY_REFRESH_FAILED: 'E_HISTORY_REFRESH_FAILED',
  UNKNOWN: 'E_UNKNOWN',
} as const

export type VfsErrorCode = (typeof VFS_ERROR_CODES)[keyof typeof VFS_ERROR_CODES]
